baseurl: "https://Koalacomk.github.io/"
publishDir: "public/"
title: Koalacomk
theme: hugo-universal-theme
languageCode: en-us
defaultContentLanguage: en
disqusShortname: devcows
googleAnalytics: ''
paginate: 10
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 2
    - identifier: faq
      name: About Me
      url: /faq/
      weight: 3
  topbar:
    - name: GitHub
      pre: <i class='fab fa-2x fa-github'></i>
      url: https://github.com/Koalacomk/
      weight: 1
    - name: Facebook
      pre: <i class='fab fa-2x fa-facebook'></i>
      url: https://www.facebook.com/Koalacomk
      weight: 2
    - name: Twitter
      pre: <i class='fab fa-2x fa-twitter'></i>
      url: http://twitter.com
      weight: 3
    - name: Email
      pre: <i class='fas fa-2x fa-envelope'></i>
      url: mailto:koalacomk@gmail.com
      weight: 4
params:
  about_us: <p> I am a simple guy trying to learn lots of stuff and helping others on their path. Also, a Mathematician, Manager, Brazilian and normal guy.
    fames ac turpis egestas.</p>
  address: "<p class=\"text-uppercase\"><strong>koalacomk@gmail.com</strong>\r\n        <br>+56935290197\r\n<br>Vina del Mar\r\n
    \       <br>\r\n        <strong>Chile</strong>\r\n      </p>\r\n      "
  author: DevCows
  carousel:
    enable: no
  clients:
    enable: no
    subtitle: ''
    title: Our Clients
  contact_form_ajax: no
  copyright: Copyright (c) 2015 - 2016, YourCompany; all rights reserved.
  date_format: January 2, 2006
  default_sharing_image: img/sharing-default.png
  defaultDescription: Site template made by devcows using hugo
  defaultKeywords:
    - devows
    - hugo
    - go
  enableGoogleMaps: yes
  facebook_site: ''
  features:
    enable: no
  formspree_action: https://formspree.io/sample/of/endpoint
  googleMapsApiKey: AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y
  latitude: '-12.043333'
  logo: img/logo.png
  logo_small: img/logo-small.png
  longitude: '-77.028333'
  mainSections: blog
  recent_posts:
    enable: yes
    subtitle: My intent with this blog is to share my opinion, codes and insights about data related topics, automations, thought and insights.
    title: Sharing Tips, Thoughts and Helping Others
  see_more:
    enable: yes
    subtitle: Welcome to my page.
    title: Luiz Lucena
  style: marsala
  testimonials:
    enable: no
    subtitle: We have worked with many clients and we always like to hear they come
      out from the cooperation happy and satisfied. Have a look what our clients said
      about us.
    title: Testimonials
  topbar:
    enable: yes
    text: "<p class=\"hidden-sm hidden-xs\">Contact me on +56 935290197 or koalacomk@gmail.com</p>\r\n
      \     <p class=\"hidden-md hidden-lg\"><a href=\"#\" data-animate-hover=\"pulse\"><i
      class=\"fas fa-phone\"></i></a>\r\n      <a href=\"#\" data-animate-hover=\"pulse\"><i
      class=\"fas fa-envelope\"></i></a>\r\n      </p>\r\n      "
  twitter_site: GoHugoIO
  viewMorePostLink: /blog/
  widgets:
    categories: yes
    search: yes
    tags: yes
permalinks:
  blog: /blog/:year/:month/:day/:filename/
